### ISSUE TITLE
Password is sent to /users as plain text on registration

### ISSUE THREAD

**Issue by niklaskoopmann** [ensklc93/myVideo-client#11]
see screenshot
![image](https://github.com/user-attachments/assets/ccbdbdaa-688e-4f93-a6d2-926794048c42)

**Comment by ensklc93** [comment]
Hey @niklaskoopmann the payload is sent over https, the clear text is only viewable by user him/herself who typed the password in. In terms of security concern we need to make sure 1) everything is over https; 2) do not store sensitive data in local storage / cookies. Masking payload is doable but comes with cost, requires server support.

**Comment by niklaskoopmann** [comment]
@ensklc93 I'm just messing with you ^^ Well done, thanks for clarifying! 💯
